### ISSUE TITLE
Application not running , Cannot find module 'express-microservice-starter error thrown

### ISSUE THREAD

**Issue by Dheerajmentor** [ph0bos/express-microservice-starter#45]
Hi , 
i am new to nodejs environment and have only .net C# experience, i was looking for a bootstrap for Microservices  in nodejs and found this 

i just downloaded it and did "npm install" then "node index.js" i got below error, 
![starterkitproblem](https://user-images.githubusercontent.com/28488401/47069832-c41ee180-d1a4-11e8-9ba1-b9e49d524c51.png)

please help me solve this 

i request you guys to please make a youtube video about how one should start using it spl. one is very new in nodejs, that will help a lot. 

thank you
Dheeraj Kumar

**Comment by ph0bos** [comment]
Hi, 

It looks like you have cloned the project and run the index.js. This module isn't a "runnable" and meant to enhance an existing express application.

Please follow the "basic usage" example https://github.com/ph0bos/express-microservice-starter#basic-usage to see how this is intended to be used.

Thanks
